# Generated by Django 4.2.7 on 2023-12-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buzos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('talle', models.TextField()),
                ('cantidad_en_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pantalones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('talle', models.TextField()),
                ('cantidad_en_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='remeras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('talle', models.TextField()),
                ('cantidad_en_stock', models.IntegerField()),
            ],
        ),
    ]
